
export const INIT_APP = 'App/INIT_APP';
export const INIT_APP_ERROR = 'App/INIT_APP_ERROR';
export const INIT_APP_SUCCESS = 'App/INIT_APP_SUCCESS';

export const SET_APP_IS_LOADING = 'APP/SET_APP_IS_LOADING';

export const START_LISTEN_PUSH_NOTIFICATION = 'User/START_LISTEN_PUSH_NOTIFICATION';
export const START_LISTEN_PUSH_NOTIFICATION_ERROR = 'User/START_LISTEN_PUSH_NOTIFICATION_ERROR';
export const START_LISTEN_PUSH_NOTIFICATION_SUCCESS = 'User/START_LISTEN_PUSH_NOTIFICATION_SUCCESS';

export const STOP_LISTEN_PUSH_NOTIFICATION = 'User/STOP_LISTEN_PUSH_NOTIFICATION';
export const STOP_LISTEN_PUSH_NOTIFICATION_ERROR = 'User/STOP_LISTEN_PUSH_NOTIFICATION_ERROR';
export const STOP_LISTEN_PUSH_NOTIFICATION_SUCCESS = 'User/STOP_LISTEN_PUSH_NOTIFICATION_SUCCESS';

export const ON_NEW_DEVICE_NOTIFICATION_TOKEN = 'User/ON_NEW_DEVICE_NOTIFICATION_TOKEN';
export const ON_NEW_PUSH_NOTIFICATION = 'User/ON_NEW_PUSH_NOTIFICATION';

export const GET_LINK_INFO = 'APP/Get_Link_Info';
export const GET_LINK_INFO_SUCCESS = 'APP/Get_Link_Info_Success';

export const GET_QUICK_LINK = "GET_QUICK_LINK";
export const GET_QUICK_LINK_SUCCESS = "GET_QUICK_LINK_SUCCESS";