
export const INIT = 'User/INIT';
export const INIT_ERROR = 'User/INIT_ERROR';
export const INIT_SUCCESS = 'User/INIT_SUCCESS';

export const FETCH_USER_DATA = 'User/FETCH_USER_DATA';
export const FETCH_USER_DATA_ERROR = 'User/FETCH_USER_DATA_ERROR';
export const FETCH_USER_DATA_SUCCESS = 'User/FETCH_USER_DATA_SUCCESS';

export const SAVE_USER_DATA = 'User/SAVE_USER_DATA';
export const SAVE_USER_DATA_ERROR = 'User/SAVE_USER_DATA_ERROR';
export const SAVE_USER_DATA_SUCCESS = 'User/SAVE_USER_DATA_SUCCESS';

export const UPDATE_USER_PROFILE = 'User/UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_ERROR = 'User/UPDATE_USER_PROFILE_ERROR';
export const UPDATE_USER_PROFILE_SUCCESS = 'User/UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_BAD_FIELD_DATA = 'Auth/UPDATE_USER_PROFILE_BAD_FIELD_DATA';
