
export const INIT = 'News/INIT';
export const INIT_ERROR = 'News/INIT_ERROR';
export const INIT_SUCCESS = 'News/INIT_SUCCESS';

export const FETCH_NEWS_LIST = 'News/FETCH_NEWS_LIST';
export const FETCH_NEWS_LIST_ERROR = 'News/FETCH_NEWS_LIST_ERROR';
export const FETCH_NEWS_LIST_SUCCESS = 'News/FETCH_NEWS_LIST_SUCCESS';

export const FETCH_NEXT_PAGE_NEWS_LIST = 'News/FETCH_NEXT_PAGE_NEWS_LIST';
export const FETCH_NEXT_PAGE_NEWS_LIST_ERROR = 'News/FETCH_NEXT_PAGE_NEWS_LIST_ERROR';
export const FETCH_NEXT_PAGE_NEWS_LIST_SUCCESS = 'News/FETCH_NEXT_PAGE_NEWS_LIST_SUCCESS';

export const NAVIGATE_TO_NEWS_DETAILS = 'News/NAVIGATE_TO_NEWS_DETAILS';
export const NAVIGATE_TO_NEWS_DETAILS_ERROR = 'News/NAVIGATE_TO_NEWS_DETAILS_ERROR';
export const NAVIGATE_TO_NEWS_DETAILS_SUCCESS = 'News/NAVIGATE_TO_NEWS_DETAILS_SUCCESS';

export const SET_NEWS_READING = 'News/SET_NEWS_READING';
export const SET_NEWS_READING_ERROR = 'News/SET_NEWS_READING_ERROR';
export const SET_NEWS_READING_SUCCESS = 'News/SET_NEWS_READING_SUCCESS';
